name: build_mac

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@master
      - name: perl -V
        run: perl -V
      - name: Run build
        run: perl Build.PL && ./Build build