name: build_mac

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@master
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: curl -L http://cpanmin.us/ | perl - -n --installdeps . --with-recommends --with-suggests --with-develop --with-configure --with-feature
      - name: Run build
        run: |
            perl Build.PL
            ./Build manifest
      - name: Run test
        run: ./Build test