name: build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          - 'latest'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Install M::B
        run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure Module::Build
      - name: Install Dev modules
        run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure Test::Perl::Critic Test::Pod::Coverage Test::Pod Test::NoTabs Test::Vars Test::File::Find::Rule
      - name: Run build
        run: |
            perl Build.PL
            ./Build installdeps
            ./Build manifest
      - name: Run test
        run: ./Build test
