name: build_old

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          - '5.8'
          - '5.18'
          - '5.28'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Install cpanm
        run: curl -L http://cpanmin.us/ | perl - App::cpanminus
      - name: Install dependencies
        run: cpanm -n --installdeps . --with-recommends --with-suggests --with-develop --with-configure --with-feature
      - name: Run build
        run: |
            perl Build.PL
            ./Build manifest
      - name: Run test
        run: ./Build test
