name: build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          - 'latest'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Install M::B
        run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure Module::Build
      - name: Run build
        run: |
            perl Build.PL
            ./Build installdeps
            ./Build manifest
      - name: Run test
        run: ./Build test
      - name: Run Cover
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
            curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure Devel::Cover::Report::Coveralls
            cover -test
            cover -report coveralls
