name: build_xt

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest

    container:
      image: perl:latest

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: curl -L http://cpanmin.us/ | perl - -n --installdeps . --with-recommends --with-suggests --with-develop --with-configure --with-feature
      - name: Install Dev modules
        run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure Test::Perl::Critic Test::Pod::Coverage Test::Pod Test::NoTabs Test::Vars Test::File::Find::Rule
      - name: Run build
        run: |
            perl Build.PL
            ./Build manifest
      - name: Run test
        run: ./Build test
