name: build_windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
      - name: perl -V
        run: perl -V
      - name: Install M::B
        run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure Module::Build
      - name: Run build
        run: |
            perl Build.PL
            ./Build installdeps
            ./Build manifest
            ./Build test
